# Generated by Django 5.1.1 on 2024-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Назва')),
                ('task_description', models.TextField(verbose_name='Опис завдання')),
                ('collaborators', models.TextField(verbose_name='Працівники')),
                ('status', models.TextField(verbose_name='Статус')),
                ('priority', models.TextField(verbose_name='Пріорітет')),
                ('budget', models.TextField(verbose_name='Бюджет')),
                ('attachiments', models.FileField(upload_to='documents/')),
                ('dead_line', models.DateField(verbose_name='Дедлайн')),
            ],
        ),
    ]
