# Generated by Django 5.1.1 on 2024-10-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='attachiments',
            new_name='attachments',
        ),
    ]
