# Generated by Django 5.1.1 on 2024-11-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0002_rename_attachiments_task_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
