# Generated by Django 5.1.1 on 2024-11-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0003_alter_task_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Назва підзавдання')),
                ('task_description', models.TextField(verbose_name='Опис підзавдання')),
                ('collaborators', models.TextField(verbose_name='Працівники')),
                ('status', models.TextField(verbose_name='Статус')),
                ('priority', models.TextField(verbose_name='Пріорітет')),
                ('budget', models.TextField(verbose_name='Бюджет')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('dead_line', models.DateField(verbose_name='Дедлайн')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='main_work_window.task')),
            ],
        ),
    ]
