# Generated by Django 5.1.1 on 2024-11-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_work_window.subtask'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_work_window.task'),
        ),
    ]
