# Generated by Django 5.1.1 on 2024-11-05 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0006_comment_subtask_alter_comment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subtask',
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_work_window.task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст коментаря'),
        ),
    ]
