# Generated by Django 5.1.1 on 2024-11-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0007_remove_comment_subtask_alter_comment_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
