# Generated by Django 5.1.1 on 2024-11-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
