# Generated by Django 5.1.1 on 2024-11-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0011_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
