# Generated by Django 5.1.1 on 2024-11-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0014_comment_subtask_alter_comment_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
