# Generated by Django 5.1.1 on 2024-11-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0018_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task_title',
        ),
        migrations.AddField(
            model_name='comment',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_work_window.subtask', verbose_name='Підзавдання'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_work_window.task', verbose_name='Завдання'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Текст коментаря'),
        ),
    ]
