# Generated by Django 5.1.1 on 2024-11-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_work_window', '0019_remove_comment_task_title_comment_subtask_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
